PJDUMP bug fixes - again

diff --git a/PJDUMP b/PJDUMP
--- a/PJDUMP
+++ b/PJDUMP
@@ -1,6 +1,6 @@
 #!/bin/bash
 #PJDUMP - emulate incremental Cyber PFDUMP of <project-name> using predetermined directory names.
-#  7/19/20.  14:15 PJLOAD NEEDS TO BE REWRITTEN TO BRING PROJECT BACK TO
+#  7/19/20.  14:55 PJLOAD NEEDS TO BE REWRITTEN TO BRING PROJECT BACK TO
 #            /Windows/../StagingArea-In
 #                   FROM ../USB20FD/git-Projects ($BACKUP_PATH)
 # Usage. bash PJDUMP <backup-path> <project-name>
@@ -47,9 +47,9 @@ touch $TEMP_PATH/scratch.txt
 # check for existing backup; if exists, as permission to recycle it; if yes,
 # rm the existing backup and rename the <project-name> directory by appending
 # a '_' to the <project-name>
-date +%T >> $system_log
+date +%T >> $system_log #
 echo -e "  PJDUMP Initiated..\n  Source = $WINGIT_PATH/$2 " >> $system_log
-echo -e "  Destination = $1 "  >> $system_log
+echo -e "  Destination = $1 "  >> $system_log #
 echo -e "PJDUMP Initiated..\nSource = $WINGIT_PATH/$2 "
 echo -e "Destination = $1 "
 PJDUMP_SOURCE=$WINGIT_PATH/$2 #
@@ -58,8 +58,8 @@ PJDUMP_DEST=$1                #
 if  cd $PJDUMP_SOURCE ; then
  echo >> $TEMP_PATH/scratch.txt
 else
- date +%T >> $system_log
- echo -e "  Source path '"$PJDUMP_SOURCE"' not found.\nPJDUMP Abandoned."
+ date +%T >> $system_log #
+ echo -e "  Source path '"$PJDUMP_SOURCE"' not found.\nPJDUMP Abandoned." >> $system_log #
  echo -e "Source path '"$PJDUMP_SOURCE"' not found.\nPJDUMP Abandoned."
  exit 1
 fi
@@ -67,8 +67,8 @@ echo $PFD
 if cd $PJDUMP_DEST ; then
  echo >> $TEMP_PATH/scratch.txt
 else
-  date +%T >> $system_log
-  echo  -e "  Destination path '"$PFDUMP_DEST"' not found.\n  PJDUMP Abandoned." >> $system_log
+  date +%T >> $system_log #
+  echo  -e "  Destination path '"$PFDUMP_DEST"' not found.\n  PJDUMP Abandoned." >> $system_log #
   echo  -e "Destination path '"$PFDUMP_DEST"' not found.\nPJDUMP Abandoned."
   exit 1
 fi
@@ -76,19 +76,20 @@ export BACKUP_PATH=$1    # set backup path from 1st parameter
 # check for existing backup
 if cd $PJDUMP_DEST/$2 ; then
   echo -e "\nFile list of $PJDUMP_DEST/$2 ..." >>$TEMP_PATH/scratch.txt
-  bu_exists="IT EXISTS"
+  bu_exists=""
   ls  >>$TEMP_PATH/scratch.txt
 else
-  date +%T >> $system_log
-  echo  -e "  Destination path '"$PFDUMP_DEST/$2 "'not found." >> $system_log
-  echo "  PJDUMP will create when dumping via git clone." >> $system_log
+  bu_exists="Aint Here"
+  date +%T >> $system_log #
+  echo  -e "  Destination path '"$PFDUMP_DEST/$2 "'not found." >> $system_log #
+  echo "  PJDUMP will create when dumping via git clone." >> $system_log #
   echo -e "Destination path $PJDUMP_DEST/$2 not found."
   echo "PJDUMP will create when dumping via git clone."
 fi;
 
 # if backup exists, as permission to delete and replace with current
 #if [ $? -eq 0 ]; then
-  if [ -n $bu_exists ]; then
+  if [ -z $bu_exists ]; then
   echo -e "Backup of $2 exists..."
   read -p "OK to recycle and proceed? (y/n)"
   if [ $REPLY == 'y' ] || [ $REPLY == 'Y' ]; then
@@ -102,11 +103,15 @@ fi;
       echo -e "ready to preserve $2 on $2_..\nCurrent path = $PWD "
       read -p "Press Enter to continue..."
       mv $2 $2_
-      date +%T >> $system_log
-      echo "  Current backup preserved in $BACKUP_PATH/$2_ " >>$system_log
+      date +%T >> $system_log #
+      echo "  Current backup preserved in $BACKUP_PATH/$2_ " >>$system_log #
       echo "Current backup preserved in $2_ "
 #      popd
     fi
+  else
+    date +%T >> $system_log #
+    echo "  User canceled overwrite of existing backup." >> $system_log #
+    exit 1
   fi    # ok to recycle backup conditional
 fi
 read -p "New backup area vacant. Proceed with PJDUMP (y/n)? "
@@ -119,28 +124,28 @@ else
 fi
 # proceed with PJDUMP
 read -t1 -p " PJDUMP intiating file copy..."
-date +%T >> $system_log
-echo "  git clone $PJDUMP_SOURCE $2 " >> $system_log
+date +%T >> $system_log #
+echo "  git clone $PJDUMP_SOURCE $2 " >> $system_log #
 git clone $PJDUMP_SOURCE $2
 # see if user wants to backup .gitignore files
 # note. PWD = $BACKUP_PATH; need to move PJDUMP_SOURCE to
 # execute BU-Ignores.sh
 if [ $? -eq 0 ]; then
-  date +%T >> $system_log
-  echo -e "  Backup clone complete..."  >> $system_log
+  date +%T >> $system_log #
+  echo -e "  Backup clone complete..."  >> $system_log #
   echo -e "Backup clone complete..."
   read -p "Do you wish to backup .gitignore files? (y/n)"
   if [ $REPLY == 'y' ] || [ $REPLY == 'Y' ]; then
 #    bash ./BU-Ignores.sh $1
-     date +%T >> $system_log
-     echo "  processing .gitignores to backup." >> $system_log
+     date +%T >> $system_log #
+     echo "  processing .gitignores to backup." >> $system_log #
      cd $PJDUMP_SOURCE
      bash BU-Ignores.sh $1
   fi    # ok to recycle backup conditional
 fi
 rm $TEMP_PATH/scratch.txt
 date +%T >> $system_log
-echo -e "  PJDUMP complete."
+echo -e "  PJDUMP complete." >> $system_log #
 echo -e "\n PJDUMP complete."
 exit 0
 
